### ISSUE TITLE
Too Permissive

### ISSUE THREAD

**Issue by ghost** [Linux4Life531/TerminalAdventureGame#1]
Hi,

This is read, write, and execute privileges for ALL -- not a good idea.

https://github.com/Linux4Life531/TerminalAdventureGame/blob/c0d38dd9ded2a0b5f80aae50bdfdab9972ec623f/Setup.sh#L3

**Comment by Linux4Life531** [comment]
Great point - I will fix it. Oh, and thanks for even looking at this - the project needs a bit of help to keep moving along so any help would be appreciated very muchly.

**Comment by Linux4Life531** [comment]
I have just updated it to 700 - will that still work?

**Comment by ghost** [comment]
You're welcome, and sorry for the late reply. If you intend the program to run from somewhere in PATH, then 755 is the typical approach. If it's intended to be used by the current user, then 700 suffices.

**Comment by Linux4Life531** [comment]
Thanks very much, I will change it.

**Comment by ghost** [comment]
You're welcome. I should probably add, however, that if you have ~/bin in PATH or something, then it doesn't apply, since that's only for the current user.

**Comment by Linux4Life531** [comment]
Okay, how can I change that so it is for every user.

**Comment by ghost** [comment]
Sorry I didn't get back to you on that last question. I imagine it's all sorted now, but if not, it sounds like you want the executable to be in PATH; a good location for a **mindfully-written** program is `/usr/bin`. Otherwise, keep it to the user's own `~/bin` directory. You don't want to be throwing 'root' permissions all over the place, willy-nilly.
